/*
 * Created on 15 jul 2018 ( Time 15:07:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "actoprocesal"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="actoprocesal", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Actoprocesal.countAll", query="SELECT COUNT(x) FROM Actoprocesal x" )
} )
public class Actoprocesal implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="codAct", nullable=false, length=5)
    private String     codAct       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nombre", length=300)
    private String     nombre       ;

    @Column(name="descr", length=300)
    private String     descr        ;

	// "nroPie" (column "nroPie") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="nroPie", referencedColumnName="nroPie")
    private PiezaProcesal piezaprocesal;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Actoprocesal() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodAct( String codAct ) {
        this.codAct = codAct ;
    }
    public String getCodAct() {
        return this.codAct;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : descr ( VARCHAR ) 
    public void setDescr( String descr ) {
        this.descr = descr;
    }
    public String getDescr() {
        return this.descr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPiezaprocesal( PiezaProcesal piezaprocesal ) {
        this.piezaprocesal = piezaprocesal;
    }
    public PiezaProcesal getPiezaprocesal() {
        return this.piezaprocesal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codAct);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(descr);
        return sb.toString(); 
    } 

}
