/*
 * Created on 15 jul 2018 ( Time 15:07:19 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ctr.iii.dominio;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "CasoAgra" ( stored in table "casoagra" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class CasoAgraKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="codCas", nullable=false, length=15)
    private String     codCas       ;
    
    @Column(name="codDdo", nullable=false, length=5)
    private String     codDdo       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public CasoAgraKey() {
        super();
    }

    public CasoAgraKey( String codCas, String codDdo ) {
        super();
        this.codCas = codCas ;
        this.codDdo = codDdo ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCodCas( String value ) {
        this.codCas = value;
    }
    public String getCodCas() {
        return this.codCas;
    }

    public void setCodDdo( String value ) {
        this.codDdo = value;
    }
    public String getCodDdo() {
        return this.codDdo;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		CasoAgraKey other = (CasoAgraKey) obj; 
		//--- Attribute codCas
		if ( codCas == null ) { 
			if ( other.codCas != null ) 
				return false ; 
		} else if ( ! codCas.equals(other.codCas) ) 
			return false ; 
		//--- Attribute codDdo
		if ( codDdo == null ) { 
			if ( other.codDdo != null ) 
				return false ; 
		} else if ( ! codDdo.equals(other.codDdo) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute codCas
		result = prime * result + ((codCas == null) ? 0 : codCas.hashCode() ) ; 
		//--- Attribute codDdo
		result = prime * result + ((codDdo == null) ? 0 : codDdo.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(codCas); 
		sb.append("|"); 
		sb.append(codDdo); 
        return sb.toString();
    }
}
