/*
 * Created on 15 jul 2018 ( Time 15:07:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "eleconviccionconclusion"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="eleconviccionconclusion", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ElemConviccionConclusion.countAll", query="SELECT COUNT(x) FROM ElemConviccionConclusion x" )
} )
public class ElemConviccionConclusion implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private ElemConviccionConclusionKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="valoracion")
    private Integer    valoracion   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaIngresoDoc")
    private Date       fechaIngresoDoc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fechaEmiRes")
    private Date       fechaEmiRes  ;

	// "nroPie" (column "nroPie") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="nroPie", referencedColumnName="nroPie")
    private PiezaProcesal piezaprocesal;

    @ManyToOne
    @JoinColumn(name="codCas", referencedColumnName="codCas", insertable=false, updatable=false)
    private Caso caso        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ElemConviccionConclusion() {
		super();
		this.compositePrimaryKey = new ElemConviccionConclusionKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setCodCas( String codCas ) {
        this.compositePrimaryKey.setCodCas( codCas ) ;
    }
    public String getCodCas() {
        return this.compositePrimaryKey.getCodCas() ;
    }
    public void setNro( Integer nro ) {
        this.compositePrimaryKey.setNro( nro ) ;
    }
    public Integer getNro() {
        return this.compositePrimaryKey.getNro() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : valoracion ( INT ) 
    public void setValoracion( Integer valoracion ) {
        this.valoracion = valoracion;
    }
    public Integer getValoracion() {
        return this.valoracion;
    }

    //--- DATABASE MAPPING : fechaIngresoDoc ( DATETIME ) 
    public void setFechaIngresoDoc( Date fechaIngresoDoc ) {
        this.fechaIngresoDoc = fechaIngresoDoc;
    }
    public Date getFechaIngresoDoc() {
        return this.fechaIngresoDoc;
    }

    //--- DATABASE MAPPING : fechaEmiRes ( DATETIME ) 
    public void setFechaEmiRes( Date fechaEmiRes ) {
        this.fechaEmiRes = fechaEmiRes;
    }
    public Date getFechaEmiRes() {
        return this.fechaEmiRes;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setPiezaprocesal( PiezaProcesal piezaprocesal ) {
        this.piezaprocesal = piezaprocesal;
    }
    public PiezaProcesal getPiezaprocesal() {
        return this.piezaprocesal;
    }

    public void setCaso( Caso caso ) {
        this.caso = caso;
    }
    public Caso getCaso() {
        return this.caso;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(valoracion);
        sb.append("|");
        sb.append(fechaIngresoDoc);
        sb.append("|");
        sb.append(fechaEmiRes);
        return sb.toString(); 
    } 

}
