/*
 * Created on 15 jul 2018 ( Time 15:07:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ctr.iii.dominio;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ElemConviccionCierre" ( stored in table "eleconviccioncierre" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ElemConviccionCierreKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="codCas", nullable=false, length=15)
    private String     codCas       ;
    
    @Column(name="nro", nullable=false)
    private Integer    nro          ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ElemConviccionCierreKey() {
        super();
    }

    public ElemConviccionCierreKey( String codCas, Integer nro ) {
        super();
        this.codCas = codCas ;
        this.nro = nro ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCodCas( String value ) {
        this.codCas = value;
    }
    public String getCodCas() {
        return this.codCas;
    }

    public void setNro( Integer value ) {
        this.nro = value;
    }
    public Integer getNro() {
        return this.nro;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ElemConviccionCierreKey other = (ElemConviccionCierreKey) obj; 
		//--- Attribute codCas
		if ( codCas == null ) { 
			if ( other.codCas != null ) 
				return false ; 
		} else if ( ! codCas.equals(other.codCas) ) 
			return false ; 
		//--- Attribute nro
		if ( nro == null ) { 
			if ( other.nro != null ) 
				return false ; 
		} else if ( ! nro.equals(other.nro) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute codCas
		result = prime * result + ((codCas == null) ? 0 : codCas.hashCode() ) ; 
		//--- Attribute nro
		result = prime * result + ((nro == null) ? 0 : nro.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(codCas); 
		sb.append("|"); 
		sb.append(nro); 
        return sb.toString();
    }
}
