/*
 * Created on 15 jul 2018 ( Time 15:07:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "elementotipo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="elementotipo", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ElementoTipo.countAll", query="SELECT COUNT(x) FROM ElementoTipo x" )
} )
public class ElementoTipo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="nroEle", nullable=false)
    private Integer    nroEle       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nro")
    private Integer    nro          ;

    @Column(name="elemento", length=50)
    private String     elemento     ;

	// "codArt" (column "codArt") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="codArt", referencedColumnName="codArt")
    private Articulo articulo    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ElementoTipo() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNroEle( Integer nroEle ) {
        this.nroEle = nroEle ;
    }
    public Integer getNroEle() {
        return this.nroEle;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nro ( INT ) 
    public void setNro( Integer nro ) {
        this.nro = nro;
    }
    public Integer getNro() {
        return this.nro;
    }

    //--- DATABASE MAPPING : elemento ( VARCHAR ) 
    public void setElemento( String elemento ) {
        this.elemento = elemento;
    }
    public String getElemento() {
        return this.elemento;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setArticulo( Articulo articulo ) {
        this.articulo = articulo;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(nroEle);
        sb.append("]:"); 
        sb.append(nro);
        sb.append("|");
        sb.append(elemento);
        return sb.toString(); 
    } 

}
