/*
 * Created on 15 jul 2018 ( Time 15:07:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "fuente"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="fuente", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Fuente.countAll", query="SELECT COUNT(x) FROM Fuente x" )
} )
public class Fuente implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="nroFue", nullable=false)
    private Integer    nroFue       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nombre", length=100)
    private String     nombre       ;

    @Column(name="descr", length=200)
    private String     descr        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Fuente() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNroFue( Integer nroFue ) {
        this.nroFue = nroFue ;
    }
    public Integer getNroFue() {
        return this.nroFue;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : descr ( VARCHAR ) 
    public void setDescr( String descr ) {
        this.descr = descr;
    }
    public String getDescr() {
        return this.descr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(nroFue);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(descr);
        return sb.toString(); 
    } 

}
