/*
 * Created on 15 jul 2018 ( Time 15:07:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "hechocaso"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="hechocaso", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="HechoCaso.countAll", query="SELECT COUNT(x) FROM HechoCaso x" )
} )
public class HechoCaso implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private HechoCasoKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="hecho", length=50)
    private String     hecho        ;

	// "nroEle" (column "nroEle") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="nroEle", referencedColumnName="nroEle")
    private ElementoTipo elementotipo;

    @ManyToOne
    @JoinColumn(name="codCas", referencedColumnName="codCas", insertable=false, updatable=false)
    private Caso caso        ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public HechoCaso() {
		super();
		this.compositePrimaryKey = new HechoCasoKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setCodCas( String codCas ) {
        this.compositePrimaryKey.setCodCas( codCas ) ;
    }
    public String getCodCas() {
        return this.compositePrimaryKey.getCodCas() ;
    }
    public void setNro( Integer nro ) {
        this.compositePrimaryKey.setNro( nro ) ;
    }
    public Integer getNro() {
        return this.compositePrimaryKey.getNro() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : hecho ( VARCHAR ) 
    public void setHecho( String hecho ) {
        this.hecho = hecho;
    }
    public String getHecho() {
        return this.hecho;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setElementotipo( ElementoTipo elementotipo ) {
        this.elementotipo = elementotipo;
    }
    public ElementoTipo getElementotipo() {
        return this.elementotipo;
    }

    public void setCaso( Caso caso ) {
        this.caso = caso;
    }
    public Caso getCaso() {
        return this.caso;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(hecho);
        return sb.toString(); 
    } 

}
