/*
 * Created on 15 jul 2018 ( Time 15:07:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "investigador"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="investigador", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Investigador.countAll", query="SELECT COUNT(x) FROM Investigador x" )
} )
public class Investigador implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="codInv", nullable=false, length=5)
    private String     codInv       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nombre", length=15)
    private String     nombre       ;

    @Column(name="paterno", length=15)
    private String     paterno      ;

    @Column(name="materno", length=15)
    private String     materno      ;

    @Column(name="grado", length=50)
    private String     grado        ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Investigador() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodInv( String codInv ) {
        this.codInv = codInv ;
    }
    public String getCodInv() {
        return this.codInv;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }

    //--- DATABASE MAPPING : paterno ( VARCHAR ) 
    public void setPaterno( String paterno ) {
        this.paterno = paterno;
    }
    public String getPaterno() {
        return this.paterno;
    }

    //--- DATABASE MAPPING : materno ( VARCHAR ) 
    public void setMaterno( String materno ) {
        this.materno = materno;
    }
    public String getMaterno() {
        return this.materno;
    }

    //--- DATABASE MAPPING : grado ( VARCHAR ) 
    public void setGrado( String grado ) {
        this.grado = grado;
    }
    public String getGrado() {
        return this.grado;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codInv);
        sb.append("]:"); 
        sb.append(nombre);
        sb.append("|");
        sb.append(paterno);
        sb.append("|");
        sb.append(materno);
        sb.append("|");
        sb.append(grado);
        return sb.toString(); 
    } 

}
