/*
 * Created on 15 jul 2018 ( Time 15:07:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "persona"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="persona", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Persona.countAll", query="SELECT COUNT(x) FROM Persona x" )
} )
public class Persona implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="codPer", nullable=false, length=5)
    private String     codPer       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="paterno", length=15)
    private String     paterno      ;

    @Column(name="nombre", length=15)
    private String     nombre       ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Persona() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCodPer( String codPer ) {
        this.codPer = codPer ;
    }
    public String getCodPer() {
        return this.codPer;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : paterno ( VARCHAR ) 
    public void setPaterno( String paterno ) {
        this.paterno = paterno;
    }
    public String getPaterno() {
        return this.paterno;
    }

    //--- DATABASE MAPPING : nombre ( VARCHAR ) 
    public void setNombre( String nombre ) {
        this.nombre = nombre;
    }
    public String getNombre() {
        return this.nombre;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(codPer);
        sb.append("]:"); 
        sb.append(paterno);
        sb.append("|");
        sb.append(nombre);
        return sb.toString(); 
    } 

}
