/*
 * Created on 15 jul 2018 ( Time 15:07:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "plazoprocesal"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="plazoprocesal", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="PlazoProcesal.countAll", query="SELECT COUNT(x) FROM PlazoProcesal x" )
} )
public class PlazoProcesal implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="nroPlz", nullable=false)
    private Integer    nroPlz       ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="codFinAct", length=5)
    private String     codFinAct    ;

    @Column(name="tiempo")
    private Integer    tiempo       ;

	// "codIniAct" (column "codIniAct") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="codIniAct", referencedColumnName="codAct")
    private Actoprocesal actoprocesal;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PlazoProcesal() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setNroPlz( Integer nroPlz ) {
        this.nroPlz = nroPlz ;
    }
    public Integer getNroPlz() {
        return this.nroPlz;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : codFinAct ( VARCHAR ) 
    public void setCodFinAct( String codFinAct ) {
        this.codFinAct = codFinAct;
    }
    public String getCodFinAct() {
        return this.codFinAct;
    }

    //--- DATABASE MAPPING : tiempo ( INT ) 
    public void setTiempo( Integer tiempo ) {
        this.tiempo = tiempo;
    }
    public Integer getTiempo() {
        return this.tiempo;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setActoprocesal( Actoprocesal actoprocesal ) {
        this.actoprocesal = actoprocesal;
    }
    public Actoprocesal getActoprocesal() {
        return this.actoprocesal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(nroPlz);
        sb.append("]:"); 
        sb.append(codFinAct);
        sb.append("|");
        sb.append(tiempo);
        return sb.toString(); 
    } 

}
