/*
 * Created on 15 jul 2018 ( Time 15:07:26 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ctr.iii.dominio;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "Prueba" ( stored in table "prueba" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class PruebaKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="codCas", nullable=false, length=15)
    private String     codCas       ;
    
    @Column(name="codPie", nullable=false)
    private Integer    codPie       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public PruebaKey() {
        super();
    }

    public PruebaKey( String codCas, Integer codPie ) {
        super();
        this.codCas = codCas ;
        this.codPie = codPie ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setCodCas( String value ) {
        this.codCas = value;
    }
    public String getCodCas() {
        return this.codCas;
    }

    public void setCodPie( Integer value ) {
        this.codPie = value;
    }
    public Integer getCodPie() {
        return this.codPie;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		PruebaKey other = (PruebaKey) obj; 
		//--- Attribute codCas
		if ( codCas == null ) { 
			if ( other.codCas != null ) 
				return false ; 
		} else if ( ! codCas.equals(other.codCas) ) 
			return false ; 
		//--- Attribute codPie
		if ( codPie == null ) { 
			if ( other.codPie != null ) 
				return false ; 
		} else if ( ! codPie.equals(other.codPie) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute codCas
		result = prime * result + ((codCas == null) ? 0 : codCas.hashCode() ) ; 
		//--- Attribute codPie
		result = prime * result + ((codPie == null) ? 0 : codPie.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(codCas); 
		sb.append("|"); 
		sb.append(codPie); 
        return sb.toString();
    }
}
