/*
 * Created on 15 jul 2018 ( Time 15:07:25 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key  


package com.ctr.iii.dominio;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "prueba"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="prueba", catalog="plaproc" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="Prueba.countAll", query="SELECT COUNT(x) FROM Prueba x" )
} )
public class Prueba implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    private PruebaKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="nroPru")
    private Integer    nroPru       ;

    @Column(name="valoracion")
    private Integer    valoracion   ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="codCas", referencedColumnName="codCas", insertable=false, updatable=false)
    private Caso caso        ;

    @ManyToOne
    @JoinColumn(name="codPie", referencedColumnName="nroPie", insertable=false, updatable=false)
    private PiezaProcesal piezaprocesal;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Prueba() {
		super();
		this.compositePrimaryKey = new PruebaKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setCodCas( String codCas ) {
        this.compositePrimaryKey.setCodCas( codCas ) ;
    }
    public String getCodCas() {
        return this.compositePrimaryKey.getCodCas() ;
    }
    public void setCodPie( Integer codPie ) {
        this.compositePrimaryKey.setCodPie( codPie ) ;
    }
    public Integer getCodPie() {
        return this.compositePrimaryKey.getCodPie() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : nroPru ( INT ) 
    public void setNroPru( Integer nroPru ) {
        this.nroPru = nroPru;
    }
    public Integer getNroPru() {
        return this.nroPru;
    }

    //--- DATABASE MAPPING : valoracion ( INT ) 
    public void setValoracion( Integer valoracion ) {
        this.valoracion = valoracion;
    }
    public Integer getValoracion() {
        return this.valoracion;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCaso( Caso caso ) {
        this.caso = caso;
    }
    public Caso getCaso() {
        return this.caso;
    }

    public void setPiezaprocesal( PiezaProcesal piezaprocesal ) {
        this.piezaprocesal = piezaprocesal;
    }
    public PiezaProcesal getPiezaprocesal() {
        return this.piezaprocesal;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(nroPru);
        sb.append("|");
        sb.append(valoracion);
        return sb.toString(); 
    } 

}
